### ISSUE TITLE
Installation fails at "./run.sh manager"

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#747]
Hi,

I currently have the reproducable problem that "./run.sh manager" runs into this error:

```
TASK [osism.services.manager : Copy osismclient bash completion script] ********************************************************************************************************************************************************************************************************************************************
fatal: [manager1-stage2-az0.pco.ps-intern.de]: FAILED! => {"changed": false, "cmd": "INTERACTIVE=false osism complete >> /etc/bash_completion.d/osism", "delta": "0:00:00.020276", "end": "2023-11-06 15:25:21.287942", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2023-11-06 15:25:21.267666", "stderr": "Error response from daemon: No such container: osismclient", "stderr_lines": ["Error response from daemon: No such container: osismclient"], "stdout": "", "stdout_lines": []}
```

At the same time on manager node:
```
ubuntu@manager1-stage2-az0:~$ docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                             PORTS      NAMES
bd3b66c23a26   quay.io/osism/ceph-ansible:6.0.1           "/entrypoint.sh slee…"   21 seconds ago   Created                                       ceph-ansible
9973f4e325d7   quay.io/osism/osism-ansible:6.0.1          "/entrypoint.sh slee…"   21 seconds ago   Created                                       osism-ansible
28e95a275c32   quay.io/osism/kolla-ansible:6.0.1          "/entrypoint.sh slee…"   21 seconds ago   Created                                       kolla-ansible
378f5074ad11   quay.io/osism/ara-server:1.7.0             "sh -c '/wait && /ru…"   21 seconds ago   Created                                       manager-ara-server-1
206e6d3635fd   quay.io/osism/inventory-reconciler:6.0.1   "/sbin/tini -- /entr…"   26 seconds ago   Up 20 seconds (health: starting)              manager-inventory_reconciler-1
97b0995d66e6   redis:7.2.0-alpine                         "docker-entrypoint.s…"   26 seconds ago   Up 20 seconds (health: starting)   6379/tcp   manager-redis-1
e37d3ce5caf8   mariadb:10.11.5                            "docker-entrypoint.s…"   26 seconds ago   Up 20 seconds (health: starting)   3306/tcp   manager-mariadb-1

```

and a minute later:
```
ubuntu@manager1-stage2-az0:~$ docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED              STATUS                        PORTS                         NAMES
bd3b66c23a26   quay.io/osism/ceph-ansible:6.0.1           "/entrypoint.sh slee…"   About a minute ago   Up About a minute                                           ceph-ansible
9973f4e325d7   quay.io/osism/osism-ansible:6.0.1          "/entrypoint.sh slee…"   About a minute ago   Up About a minute                                           osism-ansible
28e95a275c32   quay.io/osism/kolla-ansible:6.0.1          "/entrypoint.sh slee…"   About a minute ago   Up About a minute                                           kolla-ansible
378f5074ad11   quay.io/osism/ara-server:1.7.0             "sh -c '/wait && /ru…"   About a minute ago   Up About a minute (healthy)   10.70.209.70:8120->8000/tcp   manager-ara-server-1
206e6d3635fd   quay.io/osism/inventory-reconciler:6.0.1   "/sbin/tini -- /entr…"   About a minute ago   Up About a minute (healthy)                                 manager-inventory_reconciler-1
97b0995d66e6   redis:7.2.0-alpine                         "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   6379/tcp                      manager-redis-1
e37d3ce5caf8   mariadb:10.11.5                            "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   3306/tcp                      manager-mariadb-1
```

When I re-run **./run.sh manager** it works fine. So I assume that there is some sort of race condition. Maybe the task " Copy osismclient bash completion script" should wait for a running osism container. Don't know why those containers stay for a while in "created" state.

Kind regards,
André.

**Comment by nerdicbynature** [comment]
However, for some reason **osism** client also does not work. There is also no **osismclient** container in **/opt/manager/docker-compose.yml**.

I can't exclude a configuration issue. 
Relevant parts of **environments/manager/configuration.yml**:
```
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

manager_version: 6.0.1
[...]
configuration_directory: /opt/configuration
```

**Comment by berendt** [comment]
This is a bug in the osism.services.manager role at the moment. We‘ll have the same behavior on the cloud in a box deployments at the moment. Will be fixed tomorrow.

**Comment by berendt** [comment]
Looks like your issue is not related to the issue in the cloud in a box deployment.

The osismclient container is available when you enable the celery integration (which is the default: https://github.com/osism/ansible-collection-services/blob/main/roles/manager/defaults/main.yml#L207-L224). Have you disabled the celery integration in your deployments? The celery integration will be non-optional in the future.

**Comment by nerdicbynature** [comment]
Thanks for the hint. Celery was actually disabled. I changed it in our Cookiecutter repo, deleted seed and manager and redeployed.

The result is same, but different.
First run still fails with
```
Error response from daemon: No such container: osismclient\", \"stderr_lines\": [\"Error response from daemon: No such container: osismclient\"]
```
in the first run. Second run is successful. 
What's more: osismclient also works.

So, that only leaves the race condition in the first run that you already adressed before.

**Comment by berendt** [comment]
I think I fixed the race condition with https://github.com/osism/ansible-collection-services/commit/db8fbc711bc420e22c49ffa857a25d8b04c08aee. With this change the task also waits for containers in state created. I also added more health checks to the other manager services.

**Comment by nerdicbynature** [comment]
Thanks, I'll recheck tmw

**Comment by nerdicbynature** [comment]
I still get "Error response from daemon: No such container: osismclient" in the first run.
osismclient container is running.

Steps to reproduce
* Setup a new seed node and a new manager node with current Ubuntu 22.04 image.
* Follow manager installation as of https://docs.osism.tech/deployment/manager.html 

Current related software versions:
```
ubuntu@manager1:~$ dpkg -l | grep -E '(docker|compose)'
ii  docker-buildx-plugin                  0.11.2-1~ubuntu.22.04~jammy             amd64        Docker Buildx cli plugin.
ii  docker-ce                             5:24.0.7-1~ubuntu.22.04~jammy           amd64        Docker: the open-source application container engine
ii  docker-ce-cli                         5:24.0.7-1~ubuntu.22.04~jammy           amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras             5:24.0.7-1~ubuntu.22.04~jammy           amd64        Rootless support for Docker.
ii  docker-compose-plugin                 2.21.0-1~ubuntu.22.04~jammy             amd64        Docker Compose (V2) plugin for the Docker CLI.
ii  python3-docker                        5.0.3-1                                 all          Python 3 wrapper to access docker.io's control socket
```

I will use a workaround by running "./run.sh manager" twice and ignore the first run.

**Comment by berendt** [comment]
As a note: for the deployment of the manager you can already use the new documentation: https://osism.github.io/docs/guides/deploy-guide/manager

**Comment by nerdicbynature** [comment]
The problem seems to be between here in osism/services/roles/manager/tasks/service.yml:

```
    - name: Do a manual start of the manager service
      ansible.builtin.command: "/usr/bin/docker compose --project-directory {{ manager_docker_compose_directory }} up -d --remove-orphans"
      changed_when: true
```

and here:

```
- name: Wait for an healthy manager service
  ansible.builtin.shell: |
    set -o pipefail
    bash -c '{ docker ps -aq \
                --filter "label=com.docker.compose.project=manager" \
                --filter "health=starting" && \
               docker ps -aq \
                --filter "label=com.docker.compose.project=manager" \
                --filter "status=created" && \
               docker ps -aq \
                --filter "label=com.docker.compose.project=manager" \
                --filter "health=unhealthy"; }' | \
    sort | uniq -u
  args:
    executable: /bin/bash
  register: result
  changed_when: false
  until: "result.stdout | length == 0"
```

The problem is that docker compose seems to create containers lazily. The second step correctly checks for unwanted statuses or healths. However, the container does not exist at that time. So the filter return an empty list and this task does not wait at all.

I think that the logic needs to be reversed: Check for all manager containers to be of status running.

**Comment by nerdicbynature** [comment]
There is also a follow up error:

```
- name: Copy osismclient bash completion script
  become: true
  ansible.builtin.shell:
    cmd: "INTERACTIVE=false osism complete >> /etc/bash_completion.d/osism"
    creates: /etc/bash_completion.d/osism
  register: result
  changed_when: false
  failed_when: result.rc != 0
  when: enable_celery|bool

```

this code creates an empty file in the first run. In a second run it does not change the empty file as it already exists.

**Comment by berendt** [comment]
Added some more improvements to the role. Can you please check again?

**Comment by nerdicbynature** [comment]
Just to document it here as well: Still facing the same issues. Containers are stuck in "created" and playbook does not detect it and continues.

Workaround: Run twice and ignore errors of first run.

**Comment by berendt** [comment]
It currently looks like the problem is related somehow to the used Docker/Containerd/Kernel versions.

**Comment by berendt** [comment]
I'll close this. If it still happens, please open it again.
